#ifndef CONFIG_HPP_INCLUDED
#define CONFIG_HPP_INCLUDED

#define COM_DEFAULT_PORT "\\\\.\\COM5"
#define COM_DEFAULT_BRATE 115200
#define COM_DEFAULT_DATA 8
#define COM_DEFAULT_STOP SerialPortStop::Two
#define COM_DEFAULT_PARITY SerialPortParity::Mark
#define COM_DEFAULT_TIMEOUT 1100

#endif // CONFIG_HPP_INCLUDED
